
################################################################
## Load vars
################################################################

- name: Load vars
  hosts: "{{ pvar_inventory_hosts_pattern }}"
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob: "{{ var_files }}"
  tags:
    - always